package com.dynamo.demo.entity;

import com.amazonaws.services.dynamodbv2.datamodeling.*;
import lombok.AllArgsConstructor;
import lombok.Data;
import lombok.NoArgsConstructor;

@Data
@AllArgsConstructor
@NoArgsConstructor
@DynamoDBTable(tableName = "catentry")
public class CatalogEntry {

    @DynamoDBHashKey(attributeName = "catentry_id")
    @DynamoDBAutoGeneratedKey
    private String catalogEntryId;

    @DynamoDBAttribute
    private String partNumber;

    @DynamoDBAttribute
    private String name;

    @DynamoDBAttribute
    private String shortDescription;

    @DynamoDBAttribute
    private CatalogEntryType catalogEntryType;
}
